[project]
name = "atlas-ftag-tools"
description = "ATLAS Flavour Tagging Tools"
authors = [{name="Sam Van Stroud"}, {name="Philipp Gadow"}]
dynamic = ["version"]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "h5py==3.8.0",
  "numpy==1.24.*",
  "PyYAML==6.0"
]

[project.urls]
"Homepage" = "https://github.com/umami-hep/atlas-ftag-tools/"

[project.optional-dependencies]
dev = [
  "black==23.1.0",
  "ruff==0.0.254",
  "pre-commit==3.1.1",
  "pytest==7.2.2",
  "pytest-cov==4.0.0",
  "pytest_notebook==0.8.1",
  "ipykernel==6.21.3",
]

[tool.setuptools]
packages = ["ftag", "ftag.hdf5"]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "ftag.__version__"}

[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
preview = "True"

[tool.ruff]
select = ["I", "E", "W", "F", "B", "UP", "ARG", "SIM", "TID", "RUF", "D2", "D3", "D4"]
ignore = ["D211", "D213", "RUF005"]
line-length = 100

[tool.ruff.pydocstyle]
convention = "numpy"  # Accepts: "google", "numpy", or "pep257".

[tool.pytest]
nb_exec_timeout = 50
nb_coverage = "True"

[mypy]
ignore_missing_imports = "True"
